# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 11:07
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=b'', max_length=150)),
                ('summary', models.TextField(blank=True, default=b'')),
                ('file', models.FileField(upload_to=data.models.get_filename_from_uuid)),
                ('file_mimetype', models.CharField(default=b'', editable=False, max_length=50)),
                ('file_extension', models.CharField(default=b'', editable=False, max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name=b'added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name=b'updated')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
