# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uuid',
            field=models.CharField(blank=True, default='730c03d5-f6fd-485f-9967-49392daf8fa0', editable=False, max_length=36),
        ),
    ]
