# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20151216_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uuid',
            field=models.CharField(blank=True, default='45124ae6-1d89-4dc4-924d-1d131acacd58', editable=False, max_length=36),
        ),
    ]
