# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20151216_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uuid',
            field=models.CharField(blank=True, default='6c0bb872-3da2-4830-8266-e8225c2c5503', editable=False, max_length=36),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_bill_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_ordered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_payed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
