# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20151216_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='uuid',
            field=models.CharField(blank=True, default='79101501-c26d-4baa-a17c-155457f87b49', editable=False, max_length=36),
        ),
    ]
