# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20151216_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date_bill_received',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='date_payed',
        ),
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='uuid',
            field=models.CharField(blank=True, default='ad0d8558-39fe-4418-aeda-043d6b8f4d3d', editable=False, max_length=36),
        ),
    ]
