# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 19:56
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20151221_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_extension',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_mimetype',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=data.models.get_filename_from_uuid),
        ),
        migrations.AlterField(
            model_name='document',
            name='uuid',
            field=models.CharField(blank=True, default='12d0746c-9159-4cbf-8c77-05f58245a3d8', editable=False, max_length=36),
        ),
    ]
