# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20151223_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uuid',
            field=models.CharField(blank=True, default='ca02b7df-8f27-44f4-b793-a95dee60984d', editable=False, max_length=36),
        ),
    ]
