# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20160117_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name=b'added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name=b'updated')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Tag')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='uuid',
            field=models.CharField(blank=True, default='e4dee114-b5bd-4754-bfc5-89520493e378', editable=False, max_length=36),
        ),
    ]
