# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20160611_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uuid',
            field=models.CharField(blank=True, default='e164fa55-67e1-4a1a-b096-c5d09fca3fe9', editable=False, max_length=36),
        ),
        migrations.AlterField(
            model_name='entry',
            name='creditable',
            field=models.CharField(choices=[(b'U', b'Unsure'), (b'Y', b'Yes'), (b'N', b'No'), (b'I', b'Ignore')], default=b'U', max_length=1),
        ),
    ]
