# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('period', models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('Y', 'Yearly')], default='M', max_length=1)),
                ('first_execution', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.Category')),
            ],
        ),
    ]
